### ISSUE TITLE
Gerber file under tools missing

### ISSUE THREAD

**Issue by Lennard92** [InnuendoPi/Brautomat#1]
Hey,

I've seen you updated the firmware under tools. Unfortunately you deleted the gerber files. Could you please reupload them? I want to build my Brautomat the next days :)

Your project is really cool. I am working in Digitalisation for AEC and your project here is really cool. I appreciate it. 

Kind regards

Leonard

**Comment by InnuendoPi** [comment]
> I've seen you updated the firmware under tools. Unfortunately you deleted the gerber files. Could you please reupload them? I want to build my Brautomat the next days :)

I recently updated my circuit board but not all testing is complete yet. Maybe next week

**Comment by InnuendoPi** [comment]
Gerber files updated
